# Generated by Django 4.2.7 on 2024-01-28 11:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("products", "__first__"),
        ("users", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting for payment", "waiting for payment"),
                            ("paid", "paid"),
                            ("sent", "sent"),
                            ("delivered", "delivered"),
                        ],
                        default="waiting for payment",
                        max_length=30,
                    ),
                ),
                (
                    "package_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("first_name", models.CharField(max_length=46, null=True)),
                ("last_name", models.CharField(max_length=46, null=True)),
                ("phone_number", models.CharField(max_length=15, null=True)),
                ("country", models.CharField(max_length=35, null=True)),
                ("city", models.CharField(max_length=35, null=True)),
                ("street", models.CharField(max_length=95, null=True)),
                ("apartment", models.CharField(default="", max_length=20)),
                ("postal_code", models.CharField(max_length=255, null=True)),
                (
                    "modified_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("items", models.ManyToManyField(blank=True, to="products.product")),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order",
            },
        ),
    ]
