[tool.flake8]
max-line-length = 88
extend-ignore = "E203, W503, D104, D100"
exclude = [
    ".git",
    "__pycache__",
    "docs/source/conf.py",
    "old",
    "build",
    "dist",
    "migrations",
]
per-file-ignores = "./tests/*: D102, D100, D101"


[tool.isort]
profile = "black"

[tool.black]
line-length = 88
target-version = ['py38']
exclude = '/(\.git|__pycache__|docs/source/conf\.py|old|build|dist)/'