# Generated by Django 4.1.1 on 2022-10-10 23:27

import api.models.category
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_userprofile_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="svg",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="category",
                validators=[api.models.category.Category.validate_svg],
            ),
        ),
    ]
