# Generated by Django 4.1.1 on 2023-03-10 11:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_category_svg"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(default=""),
        ),
    ]
