# Generated by Django 4.1.1 on 2023-03-28 17:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0011_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="items",
            field=models.ManyToManyField(blank=True, to="api.product"),
        ),
    ]
