# Generated by Django 4.1.1 on 2023-04-13 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_alter_order_items"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.userprofile",
            ),
        ),
    ]
