# Generated by Django 4.1.1 on 2023-04-14 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_order_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="cart",
            field=models.ManyToManyField(blank=True, null=True, to="api.product"),
        ),
    ]
