# Generated by Django 4.1.1 on 2023-04-24 10:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0014_userprofile_cart"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="apartament",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="order",
            name="city",
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="country",
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="first_name",
            field=models.CharField(max_length=46, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="last_name",
            field=models.CharField(max_length=46, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="phone_number",
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="postal_code",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="street",
            field=models.CharField(max_length=95, null=True),
        ),
    ]
