# Generated by Django 4.1.1 on 2023-05-20 13:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0018_alter_hash_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hash",
            name="hash",
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
