# Generated by Django 4.1.1 on 2023-05-21 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_alter_hash_hash"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hash",
            options={"verbose_name": "Hash", "verbose_name_plural": "Hashes"},
        ),
    ]
