# Generated by Django 4.1.1 on 2023-06-03 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0021_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="modified_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
