# Generated by Django 4.1.1 on 2023-06-03 13:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0022_order_modified_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="content",
        ),
        migrations.RemoveField(
            model_name="review",
            name="grade",
        ),
        migrations.AddField(
            model_name="review",
            name="communication_rating",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="delivery_rating",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="review",
            name="overall_rating",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="quality_rating",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="review_type",
            field=models.CharField(default="overall", max_length=20),
        ),
    ]
