# Generated by Django 4.2.7 on 2024-01-17 16:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="cart",
            field=models.ManyToManyField(blank=True, to="products.product"),
        ),
    ]
